/* Sala de Control Editorial: frontend estático; todo acceso sensible depende de Supabase Auth, RLS y RPC. */
import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";

const cfg = window.CVIRTUAL_ADM_CONFIG || {};
const root = document.querySelector("#app");
const state = { session:null, user:null, staff:false, firstLogin:false, view:"home", profiles:[], own:null, notifications:[], accessRequests:[], message:null, query:"" };
const supabase = cfg.supabaseUrl && cfg.supabaseAnonKey ? createClient(cfg.supabaseUrl, cfg.supabaseAnonKey) : null;
const adminScenePhotos = ["./assets/cvirtual-professional-greeting_bf6a6b47.jpg", "./assets/cvirtual-construction-worker_bb8502a2.jpg", "./assets/cvirtual-cleaning-worker_26e776c3.jpg"];
const escape = (v="") => String(v).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const money = v => new Intl.NumberFormat("es-PE", { style:"currency", currency:"PEN" }).format(Number(v || 0));
const date = v => v ? new Intl.DateTimeFormat("es-PE", { day:"2-digit", month:"short", year:"numeric" }).format(new Date(v)) : "—";
const statusPill = s => `<span class="pill ${escape(s || "pending")}">${escape((s || "pendiente").replaceAll("_"," "))}</span>`;
function notify(text, type="info") { state.message = {text,type}; if (state.user) renderApp(); else renderLogin(); setTimeout(() => { state.message = null; if (state.user) renderApp(); else renderLogin(); }, 4200); }

async function bootstrap() {
  if (!supabase) return renderConfigError();
  const { data:{ session } } = await supabase.auth.getSession();
  state.session = session; state.user = session?.user || null;
  if (state.user) await loadPortal(); else renderLogin();
  supabase.auth.onAuthStateChange(async (_event, next) => { state.session = next; state.user = next?.user || null; if (state.user) await loadPortal(); else renderLogin(); });
}
async function loadPortal() {
  state.firstLogin = Boolean(state.user?.user_metadata?.force_password_change);
  const { data: roles } = await supabase.from("staff_roles").select("role,is_active").eq("user_id", state.user.id).eq("is_active", true);
  state.staff = Boolean(roles?.some(r => r.role === "admin" || r.role === "publisher" || r.role === "finance" || r.role === "reviewer"));
  if (state.staff) {
    const [profiles, notifications, accessRequests] = await Promise.all([
      loadAdminProfiles(),
      supabase.from("admin_notifications").select("id,title,body,is_read,created_at,candidate_id").order("created_at", {ascending:false}).limit(12),
      supabase.from("client_profile_access_requests").select("id,candidate_id,user_id,email,request_status,created_at,candidate_profiles(first_name,last_name,display_name)").eq("request_status","pending").order("created_at", {ascending:false})
    ]);
    state.profiles = profiles.data || []; state.notifications = notifications.data || []; state.accessRequests = accessRequests.data || [];
  } else {
    const { data } = await loadOwnProfile();
    state.own = data || null;
  }
  renderApp();
}
const adminProfileFields = "id,dni,first_name,last_name,display_name,headline,email,whatsapp_phone,public_whatsapp_phone,profile_kind,presentation_theme,status,expires_at,created_at,candidate_qr_codes(token,is_active),candidate_payments(amount,payment_status,service_type,created_at),candidate_media(id,media_type,media_status,visibility,is_background,uploaded_at)";
const ownProfileFields = "*,candidate_qr_codes(token,is_active),candidate_payments(id,amount,payment_status,service_type,created_at),candidate_media(id,media_type,media_status,visibility,is_background,uploaded_at)";
async function loadAdminProfiles() {
  const withCommerce = await supabase.from("candidate_profiles").select(`${adminProfileFields},profile_commerce_settings(is_store_plan,product_limit)`).order("created_at", {ascending:false});
  if (!withCommerce.error) return withCommerce;
  return supabase.from("candidate_profiles").select(adminProfileFields).order("created_at", {ascending:false});
}
async function loadOwnProfile() {
  const withCommerce = await supabase.from("candidate_profiles").select(`${ownProfileFields},profile_commerce_settings(is_store_plan,product_limit)`).eq("owner_user_id", state.user.id).maybeSingle();
  if (!withCommerce.error) return withCommerce;
  return supabase.from("candidate_profiles").select(ownProfileFields).eq("owner_user_id", state.user.id).maybeSingle();
}
function renderConfigError() { root.innerHTML = `<main class="loading"><div><b>Falta configurar Supabase.</b><p>Revisa config.js con la URL y clave pública.</p></div></main>`; }
function loginShell(inner) { root.innerHTML = `<main class="login-shell"><section class="login-story"><div class="login-photo-rotation" aria-hidden="true">${adminScenePhotos.map((src,index)=>`<img src="${src}" class="photo-${index + 1}" alt="">`).join("")}</div><div class="login-ink" aria-hidden="true"></div><div class="brand"><span class="brand-mark"></span><span>CVirtual<small>CONTROL DE PERFIL Y QR</small></span></div><div class="story-copy"><span class="kicker">Panel de relación</span><h1>Tu perfil,<br><em>bajo control.</em></h1><p>Actualiza tu información, consulta la renovación y conserva la disponibilidad de tu QR. El equipo revisa y publica el video final.</p></div><span class="case-code">Acceso protegido por Supabase Auth</span></section><section class="login-card">${inner}</section></main>`; bindAuth(); }
function renderLogin() { const content = `<span class="kicker">Acceso seguro</span><h2>Entra a tu panel.</h2><p>Clientes: escribe tu DNI y clave inicial. Administración: usa <b>admi41435757</b> o tu correo administrativo.</p><form id="login-form"><div class="field"><label>DNI de cliente, usuario o correo de administración</label><input required name="identity" autocomplete="username" placeholder="Ej. 12345678, admi41435757 o admin@correo.com"></div><div class="field"><label>Contraseña</label><input required type="password" name="password" autocomplete="current-password" placeholder="Clave inicial o contraseña"></div><button class="primary full">Ingresar</button></form><div class="auth-actions"><span class="helper">La cuenta administrativa debe cambiar su clave temporal al primer uso.</span><button class="link-btn" id="reset-password">Olvidé mi contraseña</button></div>`; loginShell(content); }
function loginEmail(identity) { const value=String(identity||"").trim().toLowerCase(); if(value === "admi41435757") return "admi41435757@clientes-cvirtual.com"; return /^\d{8}$/.test(value) ? `dni-${value}@clientes-cvirtual.com` : value; }
function bindAuth() { const login = document.querySelector("#login-form"); const reset = document.querySelector("#reset-password"); if (login) login.onsubmit = async e => { e.preventDefault(); const f = new FormData(login); const { error } = await supabase.auth.signInWithPassword({email:loginEmail(f.get("identity")),password:f.get("password")}); if(error) notify("No se pudo ingresar. Revisa tu DNI/correo y contraseña.","error"); }; if(reset) reset.onclick = async () => { const identity = prompt("Escribe tu correo de administración. Si eres cliente con DNI, solicita el reinicio al equipo CVirtual."); if(!identity) return; if(/^\d{8}$/.test(identity.trim())) return notify("Por seguridad, el reinicio de una clave asociada a DNI lo realiza el equipo CVirtual.","info"); const {error}=await supabase.auth.resetPasswordForEmail(loginEmail(identity),{redirectTo:location.href}); notify(error?error.message:"Revisa tu correo para cambiar la contraseña.",error?"error":"success"); }; }
function layout(content, title, caption) { const nav = state.staff ? [["home","Resumen"],["profiles","Perfiles y QR"],["renewals","Renovaciones"],["media","Videos editados"],["notifications","Avisos"]] : [["home","Mi perfil"],["renewals","Mi renovación"],["qr","Mi QR"]]; root.innerHTML = `<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="brand-mark"></span><span>CVirtual<small>${state.staff?"ADMINISTRACIÓN":"PANEL DE CLIENTE"}</small></span></div><nav class="nav">${nav.map(([id,label])=>`<button class="${state.view===id?"active":""}" data-view="${id}">${label}</button>`).join("")}</nav><div class="side-user"><b>${escape(state.user.email)}</b>${state.staff?"Equipo CVirtual":"Cuenta de cliente"}<br><button id="logout" class="link-btn">Cerrar sesión</button></div></aside><main class="main"><header class="topbar"><div><span class="kicker">${state.staff?"Sala de control":"Gestión personal"}</span><h1>${title}</h1></div><div class="topbar-actions"><button class="secondary" id="password-btn">Cambiar contraseña</button><button class="primary" id="logout-top">Salir</button></div></header><div class="content">${state.message?`<div class="notice ${state.message.type}">${escape(state.message.text)}</div>`:""}${state.firstLogin?`<section class="notice info"><b>Primer ingreso con DNI</b><br>Tu usuario y clave inicial son tu DNI. Puedes conservarla o cambiarla cuando prefieras desde el botón “Cambiar contraseña”.</section>`:""}${content}</div></main></div>`; document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;renderApp();}); [document.querySelector("#logout"),document.querySelector("#logout-top")].filter(Boolean).forEach(b=>b.onclick=()=>supabase.auth.signOut()); document.querySelector("#password-btn").onclick=()=>showPasswordModal(false); }
function renderApp() { if (!state.user) return renderLogin(); if (state.staff) return renderAdmin(); return renderClient(); }
function renderAdmin() { const active = state.profiles.filter(p=>p.candidate_qr_codes?.[0]?.is_active).length; const expiring = state.profiles.filter(p=>p.expires_at && new Date(p.expires_at)-Date.now()<1000*60*60*24*30).length; const pending = state.profiles.filter(p=>p.status!=="published").length; const profiles = state.profiles.filter(p=>`${p.dni||""} ${p.first_name} ${p.last_name} ${p.email}`.toLowerCase().includes(state.query.toLowerCase())); let body = ""; if(state.view === "home") body = `<div class="metrics"><div class="metric"><span>Perfiles activos</span><b>${active}</b><em>QR disponibles</em></div><div class="metric"><span>Por revisar</span><b>${pending}</b><em>Pago, video o publicación</em></div><div class="metric"><span>Vencen pronto</span><b>${expiring}</b><em>Próximos 30 días</em></div><div class="metric"><span>Ingresos potenciales</span><b>${money(expiring*20)}</b><em>Renovaciones a S/ 20</em></div></div><div class="grid-two"><section class="panel-card"><h3>Reglas de servicio</h3><div class="status-line"><span>Alta inicial</span><b>S/ 40</b></div><div class="status-line"><span>Renovación cada 6 meses</span><b>S/ 20</b></div><div class="status-line"><span>Cambio de video editado</span><b>S/ 10</b></div></section><section class="panel-card"><h3>Últimos avisos</h3>${state.notifications.slice(0,4).map(n=>`<div class="status-line"><span><b>${escape(n.title)}</b><br><small>${escape(n.body||"")}</small></span><small>${date(n.created_at)}</small></div>`).join("")||"<p class='hint'>No hay avisos nuevos.</p>"}</section></div>${profilesTable(profiles.slice(0,6))}`; else if(state.view === "profiles" || state.view === "renewals" || state.view === "media") body = profilesTable(state.view === "renewals" ? profiles.filter(p=>p.expires_at) : profiles); else body = `<section class="panel-card"><h3>Centro de avisos</h3>${state.notifications.map(n=>`<div class="status-line"><span><b>${escape(n.title)}</b><br><small>${escape(n.body||"")}</small></span>${date(n.created_at)}</div>`).join("")||"<p class='hint'>No hay avisos.</p>"}</section>`; layout(body, state.view === "home"?"Resumen operativo":state.view === "profiles"?"Perfiles y disponibilidad QR":state.view === "renewals"?"Renovaciones y pagos":state.view === "media"?"Videos editados":"Avisos", "Revisa estados antes de hacer visible un QR."); injectPresentationButtons(); bindAdminActions(); }
function profilesTable(list) { return `<section><div class="section-heading"><div><h2>Expedientes de perfil</h2><p>Una publicación depende de pago validado, medio editado, tema elegido y QR habilitado.</p></div></div><div class="table-card"><div class="table-toolbar"><input id="profile-search" value="${escape(state.query)}" placeholder="Buscar DNI, nombre o correo"></div><table class="data-table"><thead><tr><th>Persona</th><th>DNI</th><th>Estado</th><th>QR</th><th>Renovación</th><th>Medio</th><th>Acciones</th></tr></thead><tbody>${list.map(p=>{ const qr=p.candidate_qr_codes?.[0]; const media=p.candidate_media?.find(m=>m.is_background); return `<tr><td><b>${escape(p.display_name||`${p.first_name} ${p.last_name}`)}</b><br><small>${escape(p.email)}</small></td><td><b>${escape(p.dni||"—")}</b></td><td>${statusPill(p.status)}</td><td>${statusPill(qr?.is_active?"active":"disabled")}</td><td><b>${date(p.expires_at)}</b></td><td>${media?statusPill(media.media_status):"<small>Sin asignar</small>"}</td><td><div class="row-actions"><button class="small-button" data-profile="${p.id}" data-action="presentation">Tema y módulos</button><button class="small-button" data-profile="${p.id}" data-action="detail">Gestionar</button><button class="small-button orange" data-profile="${p.id}" data-action="qr">${qr?.is_active?"Deshabilitar QR":"Habilitar QR"}</button></div></td></tr>`;}).join("")||`<tr><td colspan="7" class="empty">No se encontraron perfiles.</td></tr>`}</tbody></table></div></section>`; }
function accessRequestsBlock() { if (!state.accessRequests.length) return ""; return `<section class="panel-card" style="margin-bottom:18px"><h3>Solicitudes de acceso</h3>${state.accessRequests.map(r=>`<div class="status-line"><span><b>${escape(r.candidate_profiles?.display_name || `${r.candidate_profiles?.first_name || ""} ${r.candidate_profiles?.last_name || ""}`)}</b><br><small>${escape(r.email)} · ${date(r.created_at)}</small></span><span class="row-actions"><button class="small-button orange" data-access="${r.id}" data-decision="approve">Vincular</button><button class="small-button" data-access="${r.id}" data-decision="reject">Rechazar</button></span></div>`).join("")}</section>`; }
function bindAdminActions() { const search=document.querySelector("#profile-search"); if(search) search.oninput=e=>{state.query=e.target.value;renderAdmin();}; document.querySelectorAll("[data-profile]").forEach(b=>b.onclick=()=>{const p=state.profiles.find(x=>x.id===b.dataset.profile); if(b.dataset.action==="qr") toggleQr(p); else if(b.dataset.action==="presentation") showPresentationModal(p); else showProfileModal(p);}); if(state.view === "notifications" && state.accessRequests.length) { document.querySelector(".content")?.insertAdjacentHTML("afterbegin",accessRequestsBlock()); document.querySelectorAll("[data-access]").forEach(b=>b.onclick=()=>reviewAccess(b.dataset.access,b.dataset.decision==="approve")); } }

function injectPresentationButtons() { /* La acción Tema y módulos se renderiza por perfil en la tabla. */ }
const presentationModules = ["about","experience","education","questions","portfolio","catalog","services","booking","whatsapp"];
const profileKinds = [["professional","Profesional"],["restaurant","Restaurante / pizzería"],["business","Negocio local"],["automotive","Automotor"],["transport","Transporte"],["creative","Creativo"],["service","Servicio"]];
function selectedTheme(p) { return p.presentation_theme || {}; }
function showPresentationModal(p) {
  const theme = selectedTheme(p); const kind = p.profile_kind || "professional";
  openModal(`<span class="kicker">Presentación QR</span><h2>Define cómo se verá.</h2><p class="hint">La IA propone una dirección; tú eliges lo que se publica.</p><form id="presentation-form"><div class="grid-two"><div class="field"><label>Tipo de perfil</label><select name="kind">${profileKinds.map(([id,label])=>`<option value="${id}" ${id===kind?"selected":""}>${label}</option>`).join("")}</select></div><div class="field"><label>WhatsApp público</label><input name="whatsapp" value="${escape(p.public_whatsapp_phone||p.whatsapp_phone||"")}" placeholder="51999999999"></div></div><div class="field"><label>Describe el rubro para pedir criterio de IA</label><textarea name="brief" rows="3" placeholder="Ej. Pizzería artesanal, pedidos por WhatsApp y horario nocturno."></textarea></div><button type="button" class="secondary full" id="request-style">Proponer diseño con IA</button><div class="grid-two"><div class="field"><label>Nombre de tema</label><input name="theme_name" value="${escape(theme.name||"")}" placeholder="Ej. Italia nocturna"></div><div class="field"><label>Color principal</label><input name="primary" value="${escape(theme.primary||"")}" placeholder="#b62e2e"></div><div class="field"><label>Fondo</label><input name="background" value="${escape(theme.background||"")}" placeholder="#f5e8cf"></div><div class="field"><label>Color acento</label><input name="accent" value="${escape(theme.accent||"")}" placeholder="#2e7c55"></div></div><div class="field"><label>Módulos públicos</label><div class="module-checks">${presentationModules.map((module,i)=>`<label><input type="checkbox" name="profile-module" value="${module}" ${["about","whatsapp"].includes(module)?"checked":""}> ${module === "about"?"Descripción":module === "experience"?"Experiencia":module === "education"?"Estudios":module === "questions"?"Preguntas":module === "portfolio"?"Trabajos":module === "catalog"?"Catálogo":module === "services"?"Servicios":module === "booking"?"Reserva":"WhatsApp"}</label>`).join("")}</div></div><button class="primary full" type="submit">Guardar presentación</button></form>`,()=>{
    const form=document.querySelector("#presentation-form"); const button=document.querySelector("#request-style");
    button.onclick=()=>requestStyleRecommendation(p.id,form);
    form.onsubmit=async event=>{event.preventDefault(); await savePresentation(p.id,form);};
  });
}
function readPresentation(form) { const f=new FormData(form); return { kind:f.get("kind"), whatsapp:String(f.get("whatsapp")||"").replace(/\D/g,""), theme:{name:f.get("theme_name"),background:f.get("background"),primary:f.get("primary"),accent:f.get("accent")}, modules:[...form.querySelectorAll('[name="profile-module"]:checked')].map(node=>node.value) }; }
async function requestStyleRecommendation(candidateId, form) { const brief=String(new FormData(form).get("brief")||"").trim(); if(!brief) return notify("Escribe primero una descripción del rubro.","error"); const button=document.querySelector("#request-style"); button.disabled=true; button.textContent="Consultando criterio…"; const {data,error}=await supabase.functions.invoke("style-advisor",{body:{candidateId,brief,requestedKind:new FormData(form).get("kind")}}); button.disabled=false; button.textContent="Proponer diseño con IA"; if(error||data?.error) return notify(data?.error||error.message||"No se pudo consultar la IA. Despliega la función style-advisor y configura su clave.","error"); form.elements.kind.value=data.kind||form.elements.kind.value; const theme=data.theme||{}; form.elements.theme_name.value=theme.name||""; form.elements.primary.value=theme.primary||""; form.elements.background.value=theme.background||""; form.elements.accent.value=theme.accent||""; form.querySelectorAll('[name="profile-module"]').forEach(check=>check.checked=(data.modules||[]).includes(check.value)); notify("Propuesta cargada. Revísala y pulsa Guardar presentación.","success"); }
async function savePresentation(candidateId, form) { const value=readPresentation(form); const {error}=await supabase.rpc("admin_apply_profile_presentation",{p_candidate_id:candidateId,p_kind:value.kind,p_theme:value.theme,p_whatsapp:value.whatsapp||null}); if(error) return notify(error.message,"error"); const {error:deleteError}=await supabase.from("profile_modules").delete().eq("candidate_id",candidateId); if(deleteError) return notify(deleteError.message,"error"); if(value.modules.length){const {error:insertError}=await supabase.from("profile_modules").insert(value.modules.map((module,index)=>({candidate_id:candidateId,module_key:module,is_enabled:true,display_order:index}))); if(insertError)return notify(insertError.message,"error");} document.querySelector(".modal-backdrop")?.remove(); notify("Presentación guardada. Puedes continuar con aprobación, video y publicación.","success"); await loadPortal(); }
async function toggleQr(p) { const enabled=!p.candidate_qr_codes?.[0]?.is_active; if(!confirm(`${enabled?"Habilitar":"Deshabilitar"} el QR de ${p.display_name||p.first_name}?`)) return; const {error}=await supabase.rpc("admin_set_qr_enabled",{p_candidate_id:p.id,p_enabled:enabled}); if(error) return notify(error.message,"error"); notify(`QR ${enabled?"habilitado":"deshabilitado"}.`,"success"); await loadPortal(); }
function showProfileModal(p) { const media=p.candidate_media||[]; openModal(`<span class="kicker">Expediente</span><h2>${escape(p.display_name||`${p.first_name} ${p.last_name}`)}</h2><p class="hint">${escape(p.email)} · ${escape(p.headline||"Sin titular profesional")}</p><div class="grid-two"><div><div class="field"><label>Servicio de pago</label><select id="service-type"><option value="renewal_6m">Renovación 6 meses — S/ 20</option><option value="video_change">Cambio de video — S/ 10</option><option value="initial_registration">Alta inicial — S/ 40</option></select></div><button class="primary full" id="record-payment">Registrar pago validado</button></div><div class="video-upload"><b>Subir video editado</b><p class="hint">MP4, WEBM o MOV. El archivo se guarda privado y queda listo para publicar.</p><input id="edited-video" type="file" accept="video/mp4,video/webm,video/quicktime"><button class="secondary full" id="upload-video" style="margin-top:10px">Guardar video editado</button></div></div><div class="status-line"><span>Medios registrados</span><b>${media.length}</b></div><div class="status-line"><span>Vigencia actual</span><b>${date(p.expires_at)}</b></div><div class="status-line"><span>Estado público</span>${statusPill(p.status)}</div><div class="row-actions" style="margin-top:16px"><button class="secondary" id="approve-profile">Aprobar perfil</button><button class="primary" id="publish-profile">Publicar perfil</button><button class="danger" id="unpublish-profile">Ocultar perfil</button></div>`, async () => { document.querySelector("#record-payment").onclick=()=>recordPayment(p.id); document.querySelector("#upload-video").onclick=()=>uploadEditedVideo(p.id); document.querySelector("#approve-profile").onclick=()=>reviewProfile(p.id,true); document.querySelector("#publish-profile").onclick=()=>publishProfile(p.id); document.querySelector("#unpublish-profile").onclick=()=>unpublishProfile(p.id); }); }
function openModal(html, bind) { const layer=document.createElement("div"); layer.className="modal-backdrop"; layer.innerHTML=`<section class="modal"><header><div>${html}</div><button class="modal-close" aria-label="Cerrar">×</button></header></section>`; document.body.append(layer); layer.querySelector(".modal-close").onclick=()=>layer.remove(); bind?.(); }
async function recordPayment(candidateId) { const type=document.querySelector("#service-type").value; const {error}=await supabase.rpc("admin_record_service_payment",{p_candidate_id:candidateId,p_service_type:type}); if(error) return notify(error.message,"error"); document.querySelector(".modal-backdrop")?.remove(); notify("Pago registrado y vigencia actualizada.","success"); await loadPortal(); }
async function uploadEditedVideo(candidateId) { const file=document.querySelector("#edited-video").files?.[0]; if(!file) return notify("Selecciona el video editado.","error"); const name=file.name.replace(/[^a-zA-Z0-9._-]/g,"-"); const path=`${candidateId}/edited-${Date.now()}-${name}`; const {error:upErr}=await supabase.storage.from("candidate-videos").upload(path,file,{contentType:file.type}); if(upErr) return notify(upErr.message,"error"); const {data:media,error:medErr}=await supabase.from("candidate_media").insert({candidate_id:candidateId,media_type:"video",provider:"external",provider_asset_id:path,media_status:"uploading",visibility:"private",is_background:false,metadata:{storage_provider:"supabase_storage",storage_bucket:"candidate-videos",storage_path:path,edited_by_admin:true}}).select().single(); if(medErr) return notify(medErr.message,"error"); const {error:readyErr}=await supabase.rpc("admin_mark_media_ready",{p_media_id:media.id}); if(readyErr) return notify(readyErr.message,"error"); notify("Video editado guardado. Aprueba el perfil y selecciónalo como fondo antes de publicar.","success"); await loadPortal(); }
async function reviewProfile(id,approved){const {error}=await supabase.rpc("review_candidate_profile",{p_candidate_id:id,p_is_approved:approved,p_internal_note:null});notify(error?error.message:"Perfil aprobado.",error?"error":"success");if(!error)await loadPortal();} async function publishProfile(id){const {error:prepareError}=await supabase.rpc("admin_prepare_latest_media_background",{p_candidate_id:id});if(prepareError)return notify(prepareError.message,"error");const {error}=await supabase.rpc("publish_candidate_profile",{p_candidate_id:id});notify(error?error.message:"Perfil publicado y QR disponible.",error?"error":"success");if(!error)await loadPortal();} async function unpublishProfile(id){const {error}=await supabase.rpc("unpublish_candidate_profile",{p_candidate_id:id,p_reason:"Ocultado desde administración"});notify(error?error.message:"Perfil ocultado; QR queda en construcción.",error?"error":"success");if(!error)await loadPortal();}
function renderClient() { const p=state.own; if(!p) { layout(`<section class="panel-card"><h3>Tu acceso está en revisión</h3><p class="hint">Tu cuenta ya existe, pero un administrador debe vincularla con el perfil que registraste. Usa el mismo correo del currículo y solicita la vinculación.</p><button class="secondary" id="request-link">Solicitar vinculación</button></section>`,"Acceso de cliente","Un administrador verificará la relación con tu currículo."); bindClientActions(null); return; } let body; if(state.view==="home") body=`<div class="grid-two"><section class="panel-card"><div class="profile-card"><div class="avatar">${escape((p.first_name?.[0]||"C")+(p.last_name?.[0]||"V"))}</div><div><h3>${escape(p.display_name||`${p.first_name} ${p.last_name}`)}</h3><p>${escape(p.headline||"Completa tu titular profesional")}</p></div>${statusPill(p.status)}</div><div class="status-line"><span>Disponibilidad indicada</span><b>${escape(p.presentation_config?.availability||"Por definir")}</b></div><button class="primary full" id="edit-profile" style="margin-top:16px">Actualizar mi información</button></section><section class="panel-card"><h3>Disponibilidad del QR</h3><div class="status-line"><span>Estado del QR</span>${statusPill(p.candidate_qr_codes?.[0]?.is_active?"active":"disabled")}</div><div class="status-line"><span>Perfil público</span>${statusPill(p.status)}</div><div class="status-line"><span>Vigente hasta</span><b>${date(p.expires_at)}</b></div><p class="hint">El equipo de CVirtual habilita, publica u oculta el QR después de validar pago y video.</p></section></div>`; else if(state.view==="renewals") body=`<section class="panel-card"><h3>Mi renovación</h3><div class="status-line"><span>Vigencia actual</span><b>${date(p.expires_at)}</b></div><div class="status-line"><span>Renovación semestral</span><b>S/ 20</b></div><div class="status-line"><span>Cambio de video editado</span><b>S/ 10</b></div><p class="hint">Comunícate con CVirtual para validar el pago. La renovación aprobada extiende la disponibilidad seis meses.</p><button class="primary" id="show-renewal">Solicitar renovación</button></section>`; else body=`<section class="panel-card"><h3>Mi QR</h3><p class="hint">El QR se entrega al registrar el perfil. El enlace funciona únicamente cuando CVirtual habilita la publicación.</p><div id="qr-result" class="notice info">Consultando enlace seguro…</div></section>`; layout(body,state.view==="home"?"Mi perfil":state.view==="renewals"?"Renovación y servicios":"Mi QR","Actualiza tus datos personales; el equipo conserva el control de publicación."); bindClientActions(p); }
function bindClientActions(p) { const edit=document.querySelector("#edit-profile"); if(edit) edit.onclick=()=>showClientEdit(p); const renewal=document.querySelector("#show-renewal"); if(renewal) renewal.onclick=()=>notify("Solicitud registrada. CVirtual te indicará cómo validar el pago de S/ 20.","success"); const req=document.querySelector("#request-link"); if(req) req.onclick=()=>requestAccess(); if(state.view==="qr"&&p) loadQr(p.id); }
function showClientEdit(p){openModal(`<span class="kicker">Datos del cliente</span><h2>Actualiza tu perfil.</h2><form id="client-edit"><div class="field"><label>Nombre visible</label><input name="display_name" value="${escape(p.display_name||"")}"></div><div class="field"><label>Titular profesional</label><input name="headline" value="${escape(p.headline||"")}"></div><div class="field"><label>Resumen profesional</label><textarea name="professional_summary" rows="4">${escape(p.professional_summary||"")}</textarea></div><div class="field"><label>Disponibilidad</label><select name="availability"><option ${p.presentation_config?.availability==="Disponible"?"selected":""}>Disponible</option><option ${p.presentation_config?.availability==="En búsqueda"?"selected":""}>En búsqueda</option><option ${p.presentation_config?.availability==="No disponible"?"selected":""}>No disponible</option></select></div><div class="field"><label>WhatsApp</label><input name="whatsapp_phone" value="${escape(p.whatsapp_phone||"")}"></div><button class="primary full">Guardar cambios</button></form>`,()=>{document.querySelector("#client-edit").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const presentation_config={...(p.presentation_config||{}),availability:f.get("availability")};const {error}=await supabase.from("candidate_profiles").update({display_name:f.get("display_name"),headline:f.get("headline"),professional_summary:f.get("professional_summary"),whatsapp_phone:f.get("whatsapp_phone"),presentation_config}).eq("id",p.id);if(error)return notify(error.message,"error");document.querySelector(".modal-backdrop")?.remove();notify("Perfil actualizado.","success");await loadPortal();};});}
async function loadQr(id){const el=document.querySelector("#qr-result"); const {data,error}=await supabase.rpc("get_my_qr",{p_candidate_id:id});el.className="notice "+(error?"error":"success");el.innerHTML=error?escape(error.message):`<b>Enlace del QR:</b><br><a href="${escape(data.url)}" target="_blank" rel="noreferrer">${escape(data.url)}</a>`;} async function requestAccess(){const {error}=await supabase.rpc("request_client_profile_access",{p_email:state.user.email});notify(error?error.message:"Solicitud enviada al administrador.",error?"error":"success");} async function reviewAccess(requestId,approved){const {error}=await supabase.rpc("admin_grant_client_profile_access",{p_request_id:requestId,p_approve:approved});notify(error?error.message:(approved?"Cuenta vinculada al perfil.":"Solicitud rechazada."),error?"error":"success");if(!error)await loadPortal();}
function showPasswordModal(force=false){openModal(`<span class="kicker">${force?"Primer ingreso":"Seguridad"}</span><h2>${force?"Protege tu cuenta.":"Cambia tu contraseña."}</h2><p class="hint">${force?"Tu DNI fue la clave inicial. Define una contraseña nueva antes de continuar.":"Usa una contraseña de al menos 8 caracteres."}</p><form id="password-form" onsubmit="return false"><div class="field"><label>Nueva contraseña</label><input required minlength="8" type="password" name="password" placeholder="Mínimo 8 caracteres"></div><button type="button" class="primary full" id="save-password">Actualizar contraseña</button></form>`,()=>{if(force)document.querySelector(".modal-close")?.remove();const form=document.querySelector("#password-form");const save=document.querySelector("#save-password");const applyPassword=async()=>{const password=String(new FormData(form).get("password")||"");if(password.length<8)return notify("La nueva contraseña debe tener al menos 8 caracteres.","error");save.disabled=true;save.textContent="Actualizando…";const {data,error}=await supabase.auth.updateUser({password,data:{...(state.user?.user_metadata||{}),force_password_change:false}});if(error){save.disabled=false;save.textContent="Actualizar contraseña";return notify(error.message,"error");}state.user=data.user||state.user;state.firstLogin=false;document.querySelector(".modal-backdrop")?.remove();notify("Contraseña actualizada. Tu cuenta quedó protegida.","success");await loadPortal();};form.onsubmit=e=>{e.preventDefault();applyPassword();};save.onclick=applyPassword;});}
bootstrap();

// Extensión comercial: conserva el panel oscuro existente y añade el plan Tienda virtual sin cambiar los flujos de QR ni de video.
const renderAdminBase = renderAdmin;
renderAdmin = function () {
  renderAdminBase();
  if (!state.staff || state.view !== "home") return;
  const servicePanel = [...document.querySelectorAll(".panel-card")].find((panel) => panel.querySelector("h3")?.textContent.trim() === "Reglas de servicio");
  if (!servicePanel || servicePanel.querySelector("[data-store-prices]")) return;
  servicePanel.insertAdjacentHTML("beforeend", `<div data-store-prices><div class="status-line"><span>Tienda virtual · creación</span><b>S/ 60</b></div><div class="status-line"><span>Tienda virtual · mantenimiento</span><b>S/ 30</b></div></div>`);
};

const showPresentationModalBase = showPresentationModal;
showPresentationModal = function (profile) {
  showPresentationModalBase(profile);
  const form = document.querySelector("#presentation-form");
  const briefField = form?.querySelector('textarea[name="brief"]')?.closest(".field");
  if (!form || !briefField || form.elements.store_plan) return;
  const hasStorePlan = Boolean(profile.profile_commerce_settings?.[0]?.is_store_plan);
  briefField.insertAdjacentHTML("beforebegin", `<section class="commerce-control"><div><b>Tienda virtual</b><p class="hint">Hasta 10 productos. Creación S/ 60 y mantenimiento S/ 30.</p></div><label class="switch-row"><input type="checkbox" name="store_plan" ${hasStorePlan ? "checked" : ""}> Activar tienda</label></section>`);
};

const savePresentationBase = savePresentation;
savePresentation = async function (candidateId, form) {
  const isStorePlan = Boolean(form.elements.store_plan?.checked);
  const { error } = await supabase.rpc("admin_set_commerce_plan", { p_candidate_id: candidateId, p_is_store_plan: isStorePlan, p_product_limit: 10 });
  if (error) return notify(`No se pudo guardar el plan de tienda: ${error.message}. Ejecuta primero 006_store_plan.sql.`, "error");
  return savePresentationBase(candidateId, form);
};

const showProfileModalBase = showProfileModal;
showProfileModal = function (profile) {
  showProfileModalBase(profile);
  const select = document.querySelector("#service-type");
  if (!select || select.querySelector('option[value="store_setup"]')) return;
  select.insertAdjacentHTML("beforeend", `<option value="store_setup">Tienda virtual · creación — S/ 60</option><option value="store_maintenance">Tienda virtual · mantenimiento — S/ 30</option>`);
};
